const fs = require('fs');
let code = fs.readFileSync('src/app/(app)/chat/[conversationId]/page.tsx', 'utf8');

const regex = /if\s*\(loading\)\s*\{[\s\S]*?animate-spin[\s\S]*?\}/m;

const replacement = "if (loading) {\n    return (\n      <div className=\"flex flex-col flex-1 z-10 overflow-hidden relative bg-[#F8FAFC] dark:bg-[#0B0D12]\">\n        {/* Header Skeleton */}\n        <header className=\"flex items-center justify-between px-5 py-3.5 border-b border-gray-200 dark:border-[#252A34] bg-white/80 dark:bg-[#0B0D12]/80 min-h-[64px]\">\n          <div className=\"flex items-center gap-3\">\n            <div className=\"w-10 h-10 md:hidden bg-gray-200 dark:bg-[#1A1E29] rounded-xl animate-pulse\" />\n            <div className=\"flex items-center gap-3\">\n              <div className=\"w-10 h-10 rounded-full bg-gray-200 dark:bg-[#1A1E29] animate-pulse\" />\n              <div className=\"flex flex-col gap-1.5\">\n                <div className=\"w-24 h-4 bg-gray-200 dark:bg-[#1A1E29] rounded animate-pulse\" />\n                <div className=\"w-16 h-3 bg-gray-200 dark:bg-[#1A1E29] rounded animate-pulse\" />\n              </div>\n            </div>\n          </div>\n          <div className=\"flex items-center gap-2\">\n            <div className=\"w-10 h-10 rounded-full bg-gray-200 dark:bg-[#1A1E29] animate-pulse hidden md:block\" />\n            <div className=\"w-10 h-10 rounded-full bg-gray-200 dark:bg-[#1A1E29] animate-pulse hidden md:block\" />\n            <div className=\"w-10 h-10 rounded-full bg-gray-200 dark:bg-[#1A1E29] animate-pulse\" />\n          </div>\n        </header>\n\n        {/* Message List Skeleton */}\n        <div className=\"flex-1 overflow-y-auto p-4 md:p-6 space-y-6\">\n          <div className=\"flex gap-2\">\n            <div className=\"w-8 h-8 rounded-full bg-gray-200 dark:bg-[#1A1E29] animate-pulse flex-shrink-0\" />\n            <div className=\"w-[60%] max-w-[280px] h-[80px] rounded-[18px] bg-gray-200 dark:bg-[#1A1E29] animate-pulse\" />\n          </div>\n          <div className=\"flex gap-2 flex-row-reverse mt-6\">\n            <div className=\"w-[45%] max-w-[220px] h-[60px] rounded-[18px] bg-[#8B5CF6]/10 animate-pulse\" />\n          </div>\n          <div className=\"flex gap-2 mt-6\">\n            <div className=\"w-8 h-8 rounded-full bg-gray-200 dark:bg-[#1A1E29] animate-pulse flex-shrink-0\" />\n            <div className=\"w-[70%] max-w-[320px] h-[100px] rounded-[18px] bg-gray-200 dark:bg-[#1A1E29] animate-pulse\" />\n          </div>\n        </div>\n\n        {/* Composer Skeleton */}\n        <div className=\"px-4 py-3 bg-white/80 dark:bg-[#0B0D12]/80 border-t border-gray-200 dark:border-[#252A34] min-h-[72px]\" style={{ paddingBottom: 'env(safe-area-inset-bottom)' }}>\n          <div className=\"w-full h-[44px] rounded-[20px] bg-gray-200 dark:bg-[#1A1E29] animate-pulse\" />\n        </div>\n      </div>\n    );\n  }";

if (regex.test(code)) {
    code = code.replace(regex, replacement);
    fs.writeFileSync('src/app/(app)/chat/[conversationId]/page.tsx', code);
    console.log("Success chat replace");
} else {
    console.log("No match found for chat loader");
}
